[colors.primary]
background = "#1a1a1a"
foreground = "#ffffff"

[colors.cursor]
cursor = "#d77757"
text = "#000000"

[colors.selection]
background = "#264f78"
text = "#ffffff"

[colors.normal]
black = "#000000"
red = "#d77757"
green = "#4eba65"
yellow = "#ffc107"
blue = "#b1b9f9"
magenta = "#af87ff"
cyan = "#48968c"
white = "#999999"

[colors.bright]
black = "#505050"
red = "#ff6b80"
green = "#38a660"
yellow = "#ffdf39"
blue = "#cfd7ff"
magenta = "#fd5db1"
cyan = "#0891b2"
white = "#c1c1c1"
